services:
  hash:
    image: ghcr.io/ryantiger658/hash:latest
    container_name: hash
    restart: unless-stopped
    ports:
      - "3535:3535"
    volumes:
      - vault:/vault
    environment:
      HASH_API_KEY: "change-me"
      HASH_VAULT_PATH: /vault
volumes:
  vault:
